### PR TITLE
Update unoserver to 2.2.1

### PR DESCRIPTION
**Pull request by tovmeod**

### CODE REVIEW

**Comment by jimisola** [comment]
@tovmeod Thanks for the PR. Have you built the image and tested unoserver in this PR?

**Comment by tovmeod** [comment]
I'm running this on staging, but I'm only using convert.
But I forked the client to make it work, maybe because I'm running on python 3.12.

Do you want me to open a PR there also?

**Comment by jimisola** [comment]
@tovmeod I didn't fully understand. Have you built the image of the PR that you provided and it worked?
If not and if you have the time then please download main, built and try it before I release it.

**Comment by jimisola** [comment]
I had the time to test now and just started the release of v0.4.0.

**Comment by jimisola** [comment]
The project does not build in the pipeline now for reason. I'm so far unable to figure out why.
Filed an issue report with github/build-push-action: https://github.com/docker/build-push-action/issues/1200

**Pull request merged**
